services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - path: ./.env
        required: true
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - database_network

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cloud-storage
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - database_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database_network

volumes:
  db-data:


networks:
  database_network:
    driver: bridge
